### PR TITLE
Update of the spi driver so the Frimware works with the latest esp-idf 3.0

### PR DESCRIPTION
**Pull request by krzychb**
### Tested with:
- https://github.com/espressif/esp-idf/commit/f8bda324ecde58214aaa00ab5e0da5eea9942aaf

### To Do
- Update the version of the esp-idf submodule  of the 'Firmware' repository to https://github.com/espressif/esp-idf/commit/f8bda324ecde58214aaa00ab5e0da5eea9942aaf

### Possible Improvements
- Change `badge_eink_dev_write_command_stream_u32` to really stream the data as `badge_eink_dev_write_command_stream` does
- resolve compilation warnings on deprecated functions, unused variables, etc.

### CODE REVIEW

**Comment by raboof** [comment]
Travis reports:
```
/home/travis/build/SHA2017-badge/Firmware/components/badge/./badge_power.c: In function 'badge_battery_volt_sense':
/home/travis/build/SHA2017-badge/Firmware/components/badge/./badge_power.c:27:12: error: implicit declaration of function 'adc1_get_raw' [-Werror=implicit-function-declaration]
  int val = adc1_get_raw(ADC1_CHAN_VBAT_SENSE);
```

**Comment by krzychb** [comment]
@raboof, thank you for looking into it.

This error is because function `adc1_get_raw()` has been introduced in version of esp-idf post what is currently in this repository. I have not been working with linked submodules and was not sure how to upgrade [esp-idf @ 37156d5](https://github.com/SHA2017-badge/esp-idf/tree/37156d56b34bc486ed2ca9bcb6ec023efff14bd9) to https://github.com/espressif/esp-idf/commit/f8bda324ecde58214aaa00ab5e0da5eea9942aaf in this PR. I will look into it again or please give me some hints if possible.

Optionally I can revert back to `adc1_get_voltage()`, but it is deprcated and generates extra warnings.

**Comment by basvs** [comment]
To start with: nice work! Thanks!

I think this code-improvement should also work with the older esp-idf code, so is it possible to split the patch into the spi-update and a separate patch to fix the esp-idf compatibility things?

About the _u32 methods:
The amount of available memory is not very much. We already use a lot of memory in the micropython implementation. Then I found out there's more available available, but it is only allowed to access that memory as 32-bit dwords. That's why we have the _u32 methods. I really don't know if the hardware is allowed to access that memory on a byte level, but I'm afraid it's not.

File: components/badge/badge_eink_dev.c [hunk 1]
```diff
@@ -190,42 +213,31 @@ badge_eink_dev_init(enum badge_eink_dev_t dev_type)
...
-	}
+	spi_bus_config_t buscfg = {
+        .miso_io_num = -1,  // MISO not used, we are transferring to the slave only
+        .mosi_io_num = PIN_NUM_EPD_MOSI,
+        .sclk_io_num = PIN_NUM_EPD_CLK,
+        .quadwp_io_num = -1,
+        .quadhd_io_num = -1,
+        // The maximum size sent below covers the case
+        // when the whole frame buffer is transferred to the slave
+        .max_transfer_sz = DISP_SIZE_X_B * DISP_SIZE_Y,
```
Comment (basvs) [inline components/badge/badge_eink_dev.c]: does this mean that the esp-idf code does an extra allocate of this amount of memory? If that's the case, then it might be better to use blocks of 256 bytes, or even less.

File: components/badge/badge_eink_dev.c [hunk 2]
```diff
@@ -190,42 +213,31 @@ badge_eink_dev_init(enum badge_eink_dev_t dev_type)
...
+    };
+    spi_device_interface_config_t devcfg = {
+        .clock_speed_hz = 20 * 1000 * 1000,
+        .mode = 0,  // SPI mode 0
+        .spics_io_num = PIN_NUM_EPD_CS,
+        // To Do: clarify what does it mean
+        .queue_size = 10,
```
Comment (basvs) [inline components/badge/badge_eink_dev.c]: Afaik, the queue_size is the number of requests pending at the same time. This implementation is not built for update from multiple threads at the same time. I think that a queue_size of 1 would suffice.

File: components/badge/badge_power.c [hunk 3]
```diff
@@ -24,7 +24,7 @@ int
 badge_battery_volt_sense(void)
 {
 #ifdef ADC1_CHAN_VBAT_SENSE
-	int val = adc1_get_voltage(ADC1_CHAN_VBAT_SENSE);
+	int val = adc1_get_raw(ADC1_CHAN_VBAT_SENSE);
```
Comment (basvs) [inline components/badge/badge_power.c]: could you make this a separate patch? "esp-idf update"

File: .gitignore [hunk 4]
```diff
@@ -4,3 +4,8 @@ makeenv
 custom_env.sh
 doxygen/
 .DS_Store
+
+# Eclipse configuration
+.settings
+.project
+.cproject
```
[the remark this answers is not in the document]
Comment (raboof) [reply .gitignore]: you could also consider adding them to your global gitignore instead (https://help.github.com/articles/ignoring-files/)

**Comment by krzychb** [comment]
Wow, so many comments :)
Thank you for review, they are all good and interesting points.

I will then revert some changes to minimize the number of modification and memory usage, and issue a separate PR to implement the "spi-update" to work with the existing [esp-idf @ 37156d5](https://github.com/SHA2017-badge/esp-idf/tree/37156d56b34bc486ed2ca9bcb6ec023efff14bd9) 

Then, if we are satisfied with result , I will return to this PR to handle the update to the latest esp-idf.

Does it work for you?

File: .gitignore (hunk 4 above)
[the remark this answers is not in the document]
Comment (krzychb) [reply .gitignore]: Resolved in #214

File: components/badge-first-run/badge_first_run.c [hunk 5]
```diff
@@ -594,7 +594,7 @@ badge_first_run(void)
 	cfg.nvs_enable = 0;
 	int res = esp_wifi_init(&cfg);
 	if (res == ESP_OK) {
-		res = esp_wifi_set_country(WIFI_COUNTRY_EU);
+		res = esp_wifi_set_country(WIFI_COUNTRY_POLICY_AUTO);
```
[the remark this answers is not in the document]
Comment (krzychb) [reply components/badge-first-run/badge_first_run.c]: Done as #214

File: components/badge/badge_eink_dev.c [hunk 6]
```diff
@@ -81,9 +82,8 @@ badge_eink_dev_busy_wait(void)
 void
 badge_eink_dev_intr_handler(void *arg)
 { /* in interrupt handler */
-	int gpio_state = gpio_get_level(PIN_NUM_EPD_BUSY);
-
 #ifdef CONFIG_SHA_BADGE_EINK_DEBUG
+    int gpio_state = gpio_get_level(PIN_NUM_EPD_BUSY);
```
[the remark this answers is not in the document]
Comment (krzychb) [reply components/badge/badge_eink_dev.c]: Reverted in #214

File: components/badge/badge_eink_dev.c (hunk 1 above)
Comment (krzychb) [reply components/badge/badge_eink_dev.c]: Resolved in #214

File: components/badge/badge_eink_dev.c (hunk 2 above)
Comment (krzychb) [reply components/badge/badge_eink_dev.c]: queue_size of 1 implemented in #214

File: components/badge/badge_power.c (hunk 3 above)
Comment (krzychb) [reply components/badge/badge_power.c]: The separate patch done as #215
